name: Events Demo
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main # main
      - "dev-*" # dev-nev #dev-this-is-new
      - "feat/**" # feat/new feat/new/button
    paths-ignore:
      - ".github/workflow/*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3.4.0
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        run: npm run lint
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."
